services: 
  app:
    container_name: ros_2
    build: ./ros_2/
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
      - PATH=/app/simulator/scripts:${PATH}
    volumes:
      - ros_src:/app/project
      - simulator:/app/simulator
      - stl:/app/stl
      - /tmp/.X11-unix:/tmp/.X11-unix:rw   # necessário para GUI
    network_mode: "host"   # necessário para Gazebo
    privileged: true       # opcional, ajuda com drivers gráficos
volumes:
  ros_src:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../project
  simulator:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../simulator
  stl:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../Rover_completo_STL


